name: SSH Server
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2

     - name: Failed
       run: ./dummy.sh

     - name: Start SSH Server
       if: ${{ failure() }}
       env:
         NGROK_TOKEN: ${{ secrets.2ef80dbwk08SErdTkyjqqeKCsnH_dUbz6UHWXgsXBCcDhngs }}
         SSH_PASSWORD: ${{ secrets.r1265362153. }}
       run: |
          chmod +x ./ssh-server.sh &&  ./ssh-server.sh

     - name: Sleep
       if: ${{ failure() }}
       run: sleep 6h
